version: "3"
services:
  # app:
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PORT}:${PORT}"
  # postgres:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   volumes:
  #     - ./pgdata:/opt/postgres/data

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
